### ISSUE TITLE
Integration failing after update to 2025.4.2

### ISSUE THREAD

**Issue by mooster71** [ollo69/ha-smartthinq-sensors#889]
**Describe the bug**
After upgrade of HASSIO to 2025.4.2 smartthinq integration is not loading with errors:

Setup failed for custom integration 'smartthinq_sensors': Unable to import component: cannot import name 'RECONFIGURE_NOTIFICATION_ID' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

Detected blocking call to import_module with args ('custom_components.smartthinq_sensors',) in /usr/src/homeassistant/homeassistant/loader.py, line 1052: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues.

Core:2025.4.2
Supervisor:2025.04.0
Operating System:15.2
Frontend:20250411.0

How to resolve?

**Comment by wiabts** [comment]
Same in Core 2025.4.3:

Logger: homeassistant.setup
Source: setup.py:340
First occurred: 12:14:56 (1 occurrences)
Last logged: 12:14:56

Setup failed for custom integration 'smartthinq_sensors': Unable to import component: cannot import name 'RECONFIGURE_NOTIFICATION_ID' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 9, in <module>
    from homeassistant.config_entries import (
    ...<4 lines>...
    )
ImportError: cannot import name 'RECONFIGURE_NOTIFICATION_ID' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1004, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 9, in <module>
    from homeassistant.config_entries import (
    ...<4 lines>...
    )
ImportError: cannot import name 'RECONFIGURE_NOTIFICATION_ID' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

**Comment by wiabts** [comment]
Turned out that the integration was missing from HACS after the Core update.
After searching for it and downloading it in HACS and a restart the integration started working again
