### ISSUE TITLE
After update 2023.5.0 the intergration doesn't load

### ISSUE THREAD

**Issue by xzaz** [ollo69/ha-smartthinq-sensors#534]
After the update to 2023.5.0 im getting the following error:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 228, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, SMARTTHINQ_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'```

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): docker
 - Home Assistant version installed: 2023.5.0
 - Component version installed: latest
 - Last know working version: was working on the 2023.4.x

**Output of HA logs**
See above

**Comment by drdelaney** [comment]
I recently had a different error with the 2023.5.0 update. And then I noticed there was a HACS update to v1.32.1 as well as a integration update for LG to v0.31.6 which seemed to fix my startup issues with the new 2023.5.0 update.

**Comment by xzaz** [comment]
@drdelaney You are correct; my bad, I though this was part of the core and not a custom integration. 

Solutation; just update it. Tnx

**Comment by igorsantos07** [comment]
I found an unrelated issue with the update to 2023.5.1, which was caused by the drop of `cchatdet` - fixed in the previous version of this add-on. Glad for your update suggestion, I hadn't realized that. Thanks!

**Comment by drawbars37** [comment]
I have been having a similar issue, although mine worked fine with Core-2023.5.1, but not Core-2023.5.2 or .5.3.  I made some other changes, so I cannot drop back to .5.1, but I am able to fall back to Core-2023.4.5.  I have reverted back to .4.5 three times, and the integration works perfectly.  I have then upgraded to .5.3, and the integration always fails to load properly.  This is the error message that I get:

---------- ERROR LOG ----------
Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 3:52:22 PM (1 occurrences)
Last logged: 3:52:22 PM
Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/smartthinq_sensors/init.py", line 235, in async_setup_entry
await cleanup_orphan_lge_devices(hass, config_entry.entry_id, client)
File "/config/custom_components/smartthinq_sensors/init.py", line 612, in cleanup_orphan_lge_devices
device_registry = await hass.helpers.device_registry.async_get_registry()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in getattr
value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

I reported this to the HA Core bug group two days ago.  Someone there (TheCatLady) said 1) it was working fine for her in .5.3, and that "I probably isn't a core issue."  (I don't know if she is part of the Core team, or just another forum member.)  She suggested that I report the bug here, and this seems to be related to my problem.  If you feel it is not, I would be happy to create a new bug report.

Regards,
-Bruce

**Comment by ollo69** [comment]
For sure you have an old version of this integration and you just need to upgrade to the last one. The function `async_get_registry` was deprecated and than removed from HA, and last version of this integration is not using this function from some times.

**Comment by drawbars37** [comment]
When I clicked on the latest integration, I was not asked to download the files, so I'm not sure where they went.  An installation prompt simply popped up with a URL.  I went there in Google Chrome, put in my credentials, and it redirected me to a new URL.  I copied the new URL into the empty field in the installer, and said it finished 'successfully.'

At that point, I went to the washer and dryer sensors in HA, and they were Unknown.  I then restored Core-2023.4.5, and things started working again.

Is there a better way to do a clean installation of the integration?  (I'm not trying to be stubborn or anything.  Whatever I am doing, it doesn't seem to work.  If you provide me with a specific set of steps to try, though, I will try them.)

Regards,
-BW

**Comment by ollo69** [comment]
I don't really understand what you are doing, but I don't think you are updating the integration files in correct folder. The best way to manage custom integration update is using HACS, it will manage update for you and will notify about new version. By the way you don't have to deconfigure integration every time that you update, you just need to restart HA.

**Comment by drawbars37** [comment]
I can use HACS.  But I started using ThinQ almost 6 months before I installed HACS, so the LGE app is not in the HACS list.  If I install it using HACS, are there steps I need to do to purge the old version first?

**Comment by ollo69** [comment]
HACS will probably overwrite your installation with last available version, so yes, install with HACS, I think it will work without issue.

**Comment by antoniovittozzi** [comment]
hello, I'm having issue with this integration. I created new LG Account, logged in and it says "Configuration Failed". I tried literally everything. 

HAOS on VM on Synology NAS.
