### ISSUE TITLE
Error setting up entry LGE Devices for smartthinq_sensors

### ISSUE THREAD

**Issue by simonepittis** [ollo69/ha-smartthinq-sensors#531]
After the upgrade to version Home Assistant 2023.4.6

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/core_async.py:380
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 07:40:46 (1 occurrences)
Last logged: 07:40:46

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 242, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 143, in create_client_from_token
    return await ClientAsync.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1436, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1354, in refresh
    self._auth = await self.auth.refresh(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 931, in refresh
    access_token, token_validity = await self._gateway.core.refresh_auth(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 649, in refresh_auth
    out = await self._auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 595, in _auth_request
    oauth_url = await self.get_oauth_url()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 380, in get_oauth_url
    async with self._get_session().post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

**Comment by riccardo1991** [comment]
Hello, I have the same error:

`Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/device.py:109
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 14:31:54 (3 occurrences)
Last logged: 14:39:34

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 286, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 568, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in init_device
    await self._create_coordinator()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 458, in _create_coordinator
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 463, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 475, in _async_state_update
    state = await self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 336, in poll
    res = await self._device_poll(WM_ROOT_DATA)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 698, in _device_poll
    data = await self._mon.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
    if refresh_auth := await self._refresh_auth():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth
    async with Monitor._client_lock:
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 114, in acquire
    await fut
asyncio.exceptions.CancelledError`

**Comment by jmlt** [comment]
Hello. I'm having the exact same issue.

**Comment by jeroen911** [comment]
I have te same error:
Home Assistant 2023.4.5
Supervisor 2023.04.1
Operating System 10.0
Frontend-versie: 20230411.1 - latest


Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/device.py:109
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 16:08:09 (2 occurrences)
Last logged: 16:10:45

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 286, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 568, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in init_device
    await self._create_coordinator()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 458, in _create_coordinator
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 463, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 475, in _async_state_update
    state = await self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 914, in poll
    res = await self._device_poll(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 698, in _device_poll
    data = await self._mon.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
    if refresh_auth := await self._refresh_auth():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth
    async with Monitor._client_lock:
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 114, in acquire
    await fut
asyncio.exceptions.CancelledError

**Comment by stuartwhiteford** [comment]
Piling on with the same issue...

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 9.5
Frontend 20230411.1 - latest

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/device.py:109
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 15:34:13 (1 occurrences)
Last logged: 15:34:13

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 286, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 568, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in init_device
    await self._create_coordinator()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 458, in _create_coordinator
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 463, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 475, in _async_state_update
    state = await self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 336, in poll
    res = await self._device_poll(WM_ROOT_DATA)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 689, in _device_poll
    snapshot = await self._get_device_snapshot(thinq2_query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 634, in _get_device_snapshot
    return await self._mon.refresh(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
    if refresh_auth := await self._refresh_auth():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth
    async with Monitor._client_lock:
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 114, in acquire
    await fut
asyncio.exceptions.CancelledError
```

**Comment by jmlt** [comment]
> Hello. I'm having the exact same issue.
> 
> ```
> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/smartthinq_sensors/wideq/device.py:109
> Integration: SmartThinQ LGE Sensors (documentation, issues)
> First occurred: 14:49:47 (2 occurrences)
> Last logged: 17:07:47
> 
> Error setting up entry LGE Devices for smartthinq_sensors
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 286, in async_setup_entry
>     lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 568, in lge_devices_setup
>     if not await dev.init_device():
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in init_device
>     await self._create_coordinator()
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 458, in _create_coordinator
>     await coordinator.async_refresh()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
>     await self._async_refresh(log_failures=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
>     return await self.update_method()
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 463, in _async_update
>     await self._async_state_update()
>   File "/config/custom_components/smartthinq_sensors/__init__.py", line 475, in _async_state_update
>     state = await self._device.poll()
>   File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 336, in poll
>     res = await self._device_poll(WM_ROOT_DATA)
>   File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 689, in _device_poll
>     snapshot = await self._get_device_snapshot(thinq2_query_device)
>   File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 634, in _get_device_snapshot
>     return await self._mon.refresh(query_device)
>   File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
>     if refresh_auth := await self._refresh_auth():
>   File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth
>     async with Monitor._client_lock:
>   File "/usr/local/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
>     await self.acquire()
>   File "/usr/local/lib/python3.10/asyncio/locks.py", line 114, in acquire
>     await fut
> asyncio.exceptions.CancelledError
> ```

Somehow fixed itself. It's now working for me.

**Comment by Pharizna** [comment]
Same error here working with HomeAssistant 2023.5.0

```
Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 17:02:46 (1 occurrences)
Last logged: 17:02:46

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 217, in async_setup_entry
    await cleanup_orphan_lge_devices(hass, config_entry.entry_id, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 605, in cleanup_orphan_lge_devices
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

```

**Comment by wowtah** [comment]
Same error here after update to 2023.5:

```
Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 16:05:41 (3 occurrences)
Last logged: 16:14:21

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 214, in async_setup_entry
    await cleanup_orphan_lge_devices(hass, config_entry.entry_id, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 591, in cleanup_orphan_lge_devices
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'
```

**Comment by ollo69** [comment]
For sure the integration version you are using is not the last one. Usage of `async_get_registry` was deprecated and removed some version ago, last integration version is not using this method. Update to last release to fix the issue.

**Comment by robsonfelix** [comment]
I tried uninstalling and installing it again using HACS and it did not work.

**Comment by Pharizna** [comment]
I remove it and reinstalled…and it’s working now
