### ISSUE TITLE
After update HA to 2023.5, integration breaks

### ISSUE THREAD

**Issue by wowtah** [ollo69/ha-smartthinq-sensors#538]
My LG entitites (air conditioners) showed Unavailable after upgrading HA to 2023.5. After removing and reinstalling the integration (did the setup with the login screen and the redirection URL), the Integration has this error:

```
Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 16:05:41 (3 occurrences)
Last logged: 16:14:21

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 214, in async_setup_entry
    await cleanup_orphan_lge_devices(hass, config_entry.entry_id, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 591, in cleanup_orphan_lge_devices
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'
```

My HACS (and everything in HACS) is updated to the latest version. 

Any suggestions on how to fix this ?

**Comment by wowtah** [comment]
Should the update be visible in HACS? Or do I need to pull it from Git ?

**Comment by ollo69** [comment]
If you install integration with HACS, update is visible in HACS. If you install manually, HACS will not notify you.

**Comment by wowtah** [comment]
Okay. HACS didnt show me any update, so I removed everything and added from scratch. This fixed the issue. Thanks!
