### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fracrm** [ollo69/ha-smartthinq-sensors#918]
**Describe the bug**
The integration doesn't work with HA frontend 20251105.1 
the error is: Import error 

Error importing platform config_flow from integration smartthinq_sensors to set up smartthinq_sensors configuration entry: cannot import name 'countries' from 'pycountry' (unknown location)

**Output of HA logs**

Registratore: homeassistant.config_entries
Fonte: config_entries.py:730
Prima occorrenza: 11:05:26 (3 occorrenze)
Ultimo accesso: 12:50:15

Error importing platform config_flow from integration smartthinq_sensors to set up smartthinq_sensors configuration entry: cannot import name 'countries' from 'pycountry' (unknown location)

**Comment by boruc5004** [comment]
Downgrade the integration to v0.41.1.
That fixed it for me. Works on HA 2026.1.1
